from os.path import exists, join
from typing import Dict, List, Optional

import pandas as pd

from src.api.coin_market_cap_api import CoinMarketCapApi
from src.util.config import LISTINGS_CSV_FORMAT, LISTINGS_DATA_LOCATION
from src.util.dataframe_ops import write_csv


class ListingsStep:

    def __init__(self, timestamp: str):
        self.timestamp = timestamp
        # output dataset details
        self.listings_base_path = LISTINGS_DATA_LOCATION
        self.listings_file_format = LISTINGS_CSV_FORMAT

    @property
    def listings_csv(self) -> str:
        return join(
            self.listings_base_path, self.listings_file_format.format(self.timestamp)
        )

    def generate_listings(self) -> Optional[pd.DataFrame]:
        """Gets the listings from the upstream CoinMarketCapAPI, writes to data lake location
        as a unique .csv, and returns the DataFrame for use in other workflow steps

        Args:
            timestamp (str): UTC Timestamp in the format YYYYMMDDHHMMSS for uniqueness

        Returns:
            Optional[pd.DataFrame]: Pandas DataFrame with the Crypto listings
                if generated by this process
        """
        if not exists(self.listings_csv):
            listings = self.fetch_listings_upstream()
            # Build out a flattened dataframe
            df = pd.json_normalize(listings)
            write_csv(self.listings_csv, df)
            return df

    def fetch_listings_upstream(self) -> List[Dict]:
        """External call to the CoinMarketCapAPI to gather all listings

        Returns:
            List[Dict]: List of Coin Data
        """
        api = CoinMarketCapApi()
        listings = api.get_all_latest_listings()
        return listings
